name: gpsw-tools
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - requests=2.32.4
  - pandas=2.3.1
  - biopython
  - tqdm=4.67.1
  - r-base=4.4
  - r-tidyverse=2.0.0
  - r-cowplot=1.2.0
